##################################################################################################
# Offers service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: search
    version: "1"
  name: search
spec:
  ports:
  - port: 5051
    protocol: TCP
    targetPort: 5051
  selector:
    app: search
    version: "1"
  type: LoadBalancer


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config-python-search
data:
  agent.cfg: |-
    [agent]
    app = healthcare
    tier = searchService
    node = searchService
    [controller]
    host = XYZ.saas.appdynamics.com
    port = 80
    ssl = off
    account = ACCOUNT_NAME
    accesskey = ACCESS_KEY

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
        version: "1"
    spec:
      containers:
      - env:
        - name: APPD_PROXY_CONTROL_PATH
          value: /tmp/appd/run
        name: search
        image: sgioia/healthcare-search:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-data
            mountPath: /tmp/appd/run
          - name: agent-config
            mountPath: /opt/appdynamics/agent.cfg
            subPath: agent.cfg
        ports:
        - containerPort: 5051
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5051
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5051
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: proxy
        image: sashaz/python-proxy:v1
        imagePullPolicy: Always
        env:
          - name: APPD_PROXY_CONTROL_PATH
            value: /tmp/appd/run
        volumeMounts:
        - name: shared-data
          mountPath: /tmp/appd/run
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: agent-config
        configMap:
          name: agent-config-python-search
